project:
  type: website

website:
  favicon: assets/images/fai.png
  title: "FastAI Notebooks"
  description: "Easy-to-access FastAI course notebooks and experiments"
  site-url: https://adilsiraju.github.io/fastbook-web/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: Notebooks
    right:
      - icon: github
        href: https://github.com/adilsiraju/fastbook-web

format:
  html:
    theme: darkly
    toc: true
    toc-location: left
    code-fold: true
    code-summary: "Show code"



